
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: Host=postgres;Database=topicos_3;Username=postgres;Password=123456
      ASPNETCORE_URLS: http://+:5000
    depends_on:
      - postgres
    volumes:
      - ./data:/app/data

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: topicos_3
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: